# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"9\n\x11InferVideoRequest\x12\x12\n\nvideo_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\x1d\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\"\n\x10GetResultRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"?\n\tDetection\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x03 \x03(\x02\";\n\x0f\x46rameDetections\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.inference.Detection\"=\n\x0fInferenceResult\x12*\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x1a.inference.FrameDetections2\x9c\x01\n\x10InferenceService\x12\x42\n\nInferVideo\x12\x1c.inference.InferVideoRequest\x1a\x16.inference.JobResponse\x12\x44\n\tGetResult\x12\x1b.inference.GetResultRequest\x1a\x1a.inference.InferenceResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERVIDEOREQUEST']._serialized_start=30
  _globals['_INFERVIDEOREQUEST']._serialized_end=87
  _globals['_JOBRESPONSE']._serialized_start=89
  _globals['_JOBRESPONSE']._serialized_end=118
  _globals['_GETRESULTREQUEST']._serialized_start=120
  _globals['_GETRESULTREQUEST']._serialized_end=154
  _globals['_DETECTION']._serialized_start=156
  _globals['_DETECTION']._serialized_end=219
  _globals['_FRAMEDETECTIONS']._serialized_start=221
  _globals['_FRAMEDETECTIONS']._serialized_end=280
  _globals['_INFERENCERESULT']._serialized_start=282
  _globals['_INFERENCERESULT']._serialized_end=343
  _globals['_INFERENCESERVICE']._serialized_start=346
  _globals['_INFERENCESERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
